### ISSUE TITLE
README does not mention dependencies

### ISSUE THREAD

**Issue by LinFelix** [jabbercat/jabbercat#1]
It seems `PyQt5` is necessary and the README does not mention it.
Other dependencies that are not mentioned are
- quamash
- keyring
- xdg

**Comment by LinFelix** [comment]
and sqlalchemy

**Comment by horazont** [comment]
I replaced the half-baked instructions in the readme with a link to the more comprehensive [Testing Guide](https://jabbercat.org/testing).
