### ISSUE TITLE
The UI in MUC doesn't scroll full way down when message sent

### ISSUE THREAD

**Issue by mrDoctorWho** [jabbercat/jabbercat#13]
Steps to reproduce:
1. Have a groupchat log full enough for scrollbar to appear
2. Send a message and notice that scroll is a little bit upper than it should be

**Comment by horazont** [comment]
I think I observed that already, not sure why it happens though. Thanks for the report.

**Comment by horazont** [comment]
I think this is due to the document.scrollHeight not being accurate at the time the scrolling is triggered. I tried to workaround that by adding a delay. Please update to current develop and re-try.

**Comment by mrDoctorWho** [comment]
Delay in that case should not always work, but it does work for me currently. 

If you don't mind, I'll close this.

**Comment by horazont** [comment]
Closing is fine, but I’m curious why a delay wouldn’t work in all cases?

**Comment by mrDoctorWho** [comment]
I think there's no guarantee that the add message function will complete in 50ms.

**Comment by horazont** [comment]
Right, so it’s possible that layouting may take longer than 50ms (note that the setTimeout is at the end of the function). Do you know of any event which would tell us that layouting has finished?

**Comment by mrDoctorWho** [comment]
Actually, I think there's no such event.

**Comment by horazont** [comment]
Then for the moment, setTimeout is the best we can do, I’m afraid (I’m also not happy and would prefer it very much if we had a proper solution).
