### ISSUE TITLE
MUC display does not render all participants

### ISSUE THREAD

**Issue by ge0rg** [jabbercat/jabbercat#18]
I double-clicked a MUC from the "Roster" view, and it shows some participants correctly, while one is displayed with a broken-img avatar and full participant JID:

![image](https://user-images.githubusercontent.com/165635/31722596-c40f75ca-b41c-11e7-85b1-58c27c8a96fe.png)

**Comment by horazont** [comment]
Thanks. Those are the participants who aren’t in the MUC at the time of joining. This will be fixed when the enhancement discussed in this [aioxmpp issue](https://github.com/horazont/aioxmpp/issues/150) is implemented.

**Comment by ge0rg** [comment]
Will this also fix MUC history from users who aren't in the MUC when you join?

**Comment by horazont** [comment]
What is wrong with MUC history from users who aren’t in the MUC when you join?

**Comment by ge0rg** [comment]
Nevermind, I think I just misunderstood the linked aioxmpp issue.

**Comment by horazont** [comment]
Should be fixed with most recent aioxmpp devel branch (needs ae7afdb2). Please re-open if this is not the case.
