### ISSUE TITLE
Search input: better key bindings

### ISSUE THREAD

**Issue by ge0rg** [jabbercat/jabbercat#22]
It would be great to have the following key bindings:

- A shortcut for the `[Search...]` input box, which is also displayed in the hint. Wireshark is a great example, albeit `[Ctrl][ / ]` is a bit cumbersome on non-QWERTY.
- Use the `[Down]` arrow from the search input to get directly into the (filtered) roster list

**Comment by horazont** [comment]
It is bound to F3 already.

I’m still looking for a i18n/l10n-proof and dynamic way to embed the shortcut in the placeholder text.

**Comment by horazont** [comment]
ea6a485 binds Key_Down to put focus on the roster view when pressed in the search bar.

**Comment by horazont** [comment]
b79248c  properly embeds the shortcut in the placeholder text.
