### ISSUE TITLE
Pasting a xmpp:user@example.com link in address doesn't work

### ISSUE THREAD

**Issue by mdosch** [jabbercat/jabbercat#23]
This is pretty similar to #7 
If a JID on a website is a link to xmpp:user@example.com and the link is copied it can not be pasted into the field "Address" when adding a new contact.
But it is possible to paste an URL like "https://github.com/jabbercat/jabbercat/issues/new" there which doesn't even have an @ in the whole string so could never be anything close to a JID.

**Comment by horazont** [comment]
Should be fixed with d0bf6c1. Please re-open if it doesn’t work for you.
