### ISSUE TITLE
Horizontal scroll appears even with break-word

### ISSUE THREAD

**Issue by mrDoctorWho** [jabbercat/jabbercat#27]
Sadly, the break-word thingy didn't help.

Need to find another one.

**Comment by horazont** [comment]
FTR, I think this is some box nesting thing. I’m afraid that the layout engine doesn’t even consider the messages as things to further break down in some situations due to other "blockers".

**Comment by horazont** [comment]
Possibly related: https://stackoverflow.com/questions/5889508/using-word-wrap-break-word-within-a-table

**Comment by horazont** [comment]
I think this is a side-effect of chromium/css/html and can’t be fixed reasonably. Re-open if you can provide reasonable arguments (ideally, a CSS patch) for the opposite.
