### ISSUE TITLE
Search bar: pre-select current text when selecting search bar

### ISSUE THREAD

**Issue by ge0rg** [jabbercat/jabbercat#36]
When I press Ctrl+L, I typically want to search for a contact. If I already have a search string in there, I will end up at the last cursor position that was active before switching away from the search tab. To search for a different name, I first need to delete the current content of the search bar.

It would be great if on selecting the search bar / pressing Ctrl+L, the current content of the search bar would be put into a selection, so that typing a letter would replace the selection with what I type.

**Comment by horazont** [comment]
Great idea.

How about (in addition) clearing the search bar when (a) only a single item is in the filtered roster && (b) a conversation is started/opened by activating (double-clicking) that item?

**Comment by ge0rg** [comment]
Sounds reasonable. Would be nice to try it out to see if it is good or not.

**Comment by horazont** [comment]
@ge0rg See 4a02ce4 for the original issue and d14c2f4 (both merged) for the experiment I suggested.

Close if you agree, keep open and discuss otherwise.
