### ISSUE TITLE
Installation fails on Debian 9 (1)

### ISSUE THREAD

**Issue by cknoll** [jabbercat/jabbercat#40]
I did everything as described at https://jabbercat.org/testing/ and got the following 

    19:26 $ make
    ./utils/buildui.py -5 data/roster_msg_box_stack.ui jabbercat/ui/roster_msg_box_stack.py
    Traceback (most recent call last):
    File "./utils/buildui.py", line 29, in <module>
        uic.compileUi(args.uifile, f)
    File "/home/ck/.local/lib/python3.5/site-packages/PyQt5/uic/__init__.py", line 164, in compileUi
        winfo = compiler.UICompiler().compileUi(uifile, pyfile, from_imports, resource_suffix, import_from)
    File "/home/ck/.local/lib/python3.5/site-packages/PyQt5/uic/Compiler/compiler.py", line 110, in compileUi
        w = self.parse(input_stream, resource_suffix)
    File "/home/ck/.local/lib/python3.5/site-packages/PyQt5/uic/uiparser.py", line 1012, in parse
        self.finalize()
    File "/home/ck/.local/lib/python3.5/site-packages/PyQt5/uic/Compiler/compiler.py", line 96, in finalize
        indenter.write(s)
    File "/home/ck/.local/lib/python3.5/site-packages/PyQt5/uic/Compiler/indenter.py", line 64, in write
        self.output.write("%s%s\n" % (indent * self.level, line))
    UnicodeEncodeError: 'ascii' codec can't encode character '\u2718' in position 69: ordinal not in range(128)
    Makefile:22: recipe for target 'jabbercat/ui/roster_msg_box_stack.py' failed
    make: *** [jabbercat/ui/roster_msg_box_stack.py] Error 1

**Comment by horazont** [comment]
What was the value of ``$LANG`` during this attempt?

**Comment by cknoll** [comment]
`C`

**Comment by horazont** [comment]
Does it work with ``C.UTF-8`` or any other UTF-8 encoding?

(read: Don’t use non-UTF-8 locales with JabberCat. It’s asking for trouble I think.)

**Comment by cknoll** [comment]
Originally I tried it with `de_DE.UTF-8` which led to #41. Then I retried it with LANG=C to produce consistent English error messages.

Using `C.UTF-8` with the version from before the fix of #41 I get exactly the same error.

Now, with the new version there is progress but still some error (see last line):

    11:15 $ echo $LANG
    C.UTF-8
    (env) ✔ ~/tmp/0_stick_tmp/jctest/jabbercat [devel|✔] 
    11:15 $ make
    ./utils/buildui.py -5 data/tasks_status_widget.ui jabbercat/ui/tasks_status_widget.py
    ./utils/buildui.py -5 data/dlg_presence_modes.ui jabbercat/ui/dlg_presence_modes.py
    ./utils/buildui.py -5 data/dlg_input_jid.ui jabbercat/ui/dlg_input_jid.py
    ./utils/buildui.py -5 data/roster_tags.ui jabbercat/ui/roster_tags.py
    ./utils/buildui.py -5 data/dlg_account_manager.ui jabbercat/ui/dlg_account_manager.py
    ./utils/buildui.py -5 data/dlg_password_prompt.ui jabbercat/ui/dlg_password_prompt.py
    ./utils/buildui.py -5 data/p2p_conversation.ui jabbercat/ui/p2p_conversation.py
    ./utils/buildui.py -5 data/roster_msg_box_stack.ui jabbercat/ui/roster_msg_box_stack.py
    ./utils/buildui.py -5 data/dlg_python_console.ui jabbercat/ui/dlg_python_console.py
    ./utils/buildui.py -5 data/dlg_custom_presence_states.ui jabbercat/ui/dlg_custom_presence_states.py
    ./utils/buildui.py -5 data/dlg_add_account.ui jabbercat/ui/dlg_add_account.py
    ./utils/buildui.py -5 data/dlg_data_form.ui jabbercat/ui/dlg_data_form.py
    ./utils/buildui.py -5 data/dlg_edit_custom_presence.ui jabbercat/ui/dlg_edit_custom_presence.py
    ./utils/buildui.py -5 data/roster_msg_box.ui jabbercat/ui/roster_msg_box.py
    ./utils/buildui.py -5 data/dlg_join_muc.ui jabbercat/ui/dlg_join_muc.py
    ./utils/buildui.py -5 data/roster_tags_box.ui jabbercat/ui/roster_tags_box.py
    ./utils/buildui.py -5 data/dlg_account_editor.ui jabbercat/ui/dlg_account_editor.py
    ./utils/buildui.py -5 data/account_manager.ui jabbercat/ui/account_manager.py
    ./utils/buildui.py -5 data/dlg_add_contact.ui jabbercat/ui/dlg_add_contact.py
    ./utils/buildui.py -5 data/tag_bubble.ui jabbercat/ui/tag_bubble.py
    ./utils/buildui.py -5 data/dlg_add_account_page_credentials.ui jabbercat/ui/dlg_add_account_page_credentials.py
    ./utils/buildui.py -5 data/tasks_popup_frame.ui jabbercat/ui/tasks_popup_frame.py
    ./utils/buildui.py -5 data/tags_input.ui jabbercat/ui/tags_input.py
    ./utils/buildui.py -5 data/dlg_add_account_page_connecting.ui jabbercat/ui/dlg_add_account_page_connecting.py
    ./utils/buildui.py -5 data/main.ui jabbercat/ui/main.py
    ./utils/buildui.py -5 data/dlg_check_certificate.ui jabbercat/ui/dlg_check_certificate.py
    cd data; qtchooser -run-tool=rcc -qt=5 --binary -o ../resources.rcc resources.qrc
    test ! -d "data/emoji-java" && git clone --depth 1 https://github.com/vdurmont/emoji-java "data/emoji-java" || test -d "data/emoji-java"
    Cloning into 'data/emoji-java'...
    remote: Counting objects: 45, done.
    remote: Compressing objects: 100% (30/30), done.
    remote: Total 45 (delta 0), reused 26 (delta 0), pack-reused 0
    Unpacking objects: 100% (45/45), done.
    cd "data/emoji-java"; git pull
    Already up-to-date.
    test ! -d "data/gemoji" && git clone --depth 1 https://github.com/github/gemoji "data/gemoji" || test -d "data/gemoji"
    Cloning into 'data/gemoji'...
    remote: Counting objects: 55, done.
    remote: Compressing objects: 100% (53/53), done.
    remote: Total 55 (delta 0), reused 37 (delta 0), pack-reused 0
    Unpacking objects: 100% (55/55), done.
    cd "data/gemoji"; git pull
    Already up-to-date.
    PYTHONPATH=. python3 utils/build-emojidb.py --emoji-java data/emoji-java/src/main/resources/emojis.json --gemoji data/gemoji/db/emoji.json "data/js/emoji.json"
    failed to load emoji database

**Comment by cknoll** [comment]
Originally I tried it with `de_DE.UTF-8` which led to #41. Then I retried it with LANG=C to produce consistent English error messages.

Using `C.UTF-8` with the version from before the fix of #41 I get exactly the same error.

Now, with the new version there is progress but still some error (see last line):

    11:15 $ echo $LANG
    C.UTF-8
    (env) ✔ ~/tmp/0_stick_tmp/jctest/jabbercat [devel|✔] 
    11:15 $ make
    ./utils/buildui.py -5 data/tasks_status_widget.ui jabbercat/ui/tasks_status_widget.py
    ./utils/buildui.py -5 data/dlg_presence_modes.ui jabbercat/ui/dlg_presence_modes.py
    ./utils/buildui.py -5 data/dlg_input_jid.ui jabbercat/ui/dlg_input_jid.py
    ./utils/buildui.py -5 data/roster_tags.ui jabbercat/ui/roster_tags.py
    ./utils/buildui.py -5 data/dlg_account_manager.ui jabbercat/ui/dlg_account_manager.py
    ./utils/buildui.py -5 data/dlg_password_prompt.ui jabbercat/ui/dlg_password_prompt.py
    ./utils/buildui.py -5 data/p2p_conversation.ui jabbercat/ui/p2p_conversation.py
    ./utils/buildui.py -5 data/roster_msg_box_stack.ui jabbercat/ui/roster_msg_box_stack.py
    ./utils/buildui.py -5 data/dlg_python_console.ui jabbercat/ui/dlg_python_console.py
    ./utils/buildui.py -5 data/dlg_custom_presence_states.ui jabbercat/ui/dlg_custom_presence_states.py
    ./utils/buildui.py -5 data/dlg_add_account.ui jabbercat/ui/dlg_add_account.py
    ./utils/buildui.py -5 data/dlg_data_form.ui jabbercat/ui/dlg_data_form.py
    ./utils/buildui.py -5 data/dlg_edit_custom_presence.ui jabbercat/ui/dlg_edit_custom_presence.py
    ./utils/buildui.py -5 data/roster_msg_box.ui jabbercat/ui/roster_msg_box.py
    ./utils/buildui.py -5 data/dlg_join_muc.ui jabbercat/ui/dlg_join_muc.py
    ./utils/buildui.py -5 data/roster_tags_box.ui jabbercat/ui/roster_tags_box.py
    ./utils/buildui.py -5 data/dlg_account_editor.ui jabbercat/ui/dlg_account_editor.py
    ./utils/buildui.py -5 data/account_manager.ui jabbercat/ui/account_manager.py
    ./utils/buildui.py -5 data/dlg_add_contact.ui jabbercat/ui/dlg_add_contact.py
    ./utils/buildui.py -5 data/tag_bubble.ui jabbercat/ui/tag_bubble.py
    ./utils/buildui.py -5 data/dlg_add_account_page_credentials.ui jabbercat/ui/dlg_add_account_page_credentials.py
    ./utils/buildui.py -5 data/tasks_popup_frame.ui jabbercat/ui/tasks_popup_frame.py
    ./utils/buildui.py -5 data/tags_input.ui jabbercat/ui/tags_input.py
    ./utils/buildui.py -5 data/dlg_add_account_page_connecting.ui jabbercat/ui/dlg_add_account_page_connecting.py
    ./utils/buildui.py -5 data/main.ui jabbercat/ui/main.py
    ./utils/buildui.py -5 data/dlg_check_certificate.ui jabbercat/ui/dlg_check_certificate.py
    cd data; qtchooser -run-tool=rcc -qt=5 --binary -o ../resources.rcc resources.qrc
    test ! -d "data/emoji-java" && git clone --depth 1 https://github.com/vdurmont/emoji-java "data/emoji-java" || test -d "data/emoji-java"
    Cloning into 'data/emoji-java'...
    remote: Counting objects: 45, done.
    remote: Compressing objects: 100% (30/30), done.
    remote: Total 45 (delta 0), reused 26 (delta 0), pack-reused 0
    Unpacking objects: 100% (45/45), done.
    cd "data/emoji-java"; git pull
    Already up-to-date.
    test ! -d "data/gemoji" && git clone --depth 1 https://github.com/github/gemoji "data/gemoji" || test -d "data/gemoji"
    Cloning into 'data/gemoji'...
    remote: Counting objects: 55, done.
    remote: Compressing objects: 100% (53/53), done.
    remote: Total 55 (delta 0), reused 37 (delta 0), pack-reused 0
    Unpacking objects: 100% (55/55), done.
    cd "data/gemoji"; git pull
    Already up-to-date.
    PYTHONPATH=. python3 utils/build-emojidb.py --emoji-java data/emoji-java/src/main/resources/emojis.json --gemoji data/gemoji/db/emoji.json "data/js/emoji.json"
    failed to load emoji database

**Comment by horazont** [comment]
The last line is not an error, it’s a warning. Unfortunately, Python doesn’t print it as such by default. The build succeeded (which the exit status confirms). ``make run-debug`` should start JabberCat now just fine.

**Comment by cknoll** [comment]
Ok.
Maybe it is useful to mention that at <https://jabbercat.org/testing/>.

I think this issue can be closed.

**Comment by horazont** [comment]
There you go :-).
