### ISSUE TITLE
opentype: Missing dependency?

### ISSUE THREAD

**Issue by cknoll** [jabbercat/jabbercat#45]
After successful `make` I get the following result to  `make run-debug`:

    Platform: Linux-4.9.0-6-amd64-x86_64-with-debian-9.3
    Python: 3.5.3 (default, Jan 19 2017, 14:11:04) 
    [GCC 6.3.0 20170118]
    PyQt5: 5.9 (Qt: 5.9.1)
    Quamash: 0.6.0 (git: N/A)
    aiosasl: 0.3.1 (git: N/A)
    aioopenssl: 0.3.1 (git: N/A)
    Traceback (most recent call last):
    File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
    File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
    File "/media/workcard/workstickdir/stick_tmp/jctest/jabbercat/jabbercat/__main__.py", line 157, in <module>
        main()
    File "/media/workcard/workstickdir/stick_tmp/jctest/jabbercat/jabbercat/__main__.py", line 111, in main
        import jabbercat.main
    File "/media/workcard/workstickdir/stick_tmp/jctest/jabbercat/jabbercat/main.py", line 6, in <module>
        import aioxmpp
    File "/media/workcard/workstickdir/stick_tmp/jctest/aioxmpp/aioxmpp/__init__.py", line 114, in <module>
        from .security_layer import make as make_security_layer  # NOQA
    File "/media/workcard/workstickdir/stick_tmp/jctest/aioxmpp/aioxmpp/security_layer.py", line 128, in <module>
        import pyasn1_modules.rfc2459
    File "/media/workcard/workstickdir/stick_tmp/jctest/env/lib/python3.5/site-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
        from pyasn1.type import opentype
    ImportError: cannot import name 'opentype'

I can try to install it on my own but for the sake of testing the sanity of the install procedure, a fix in the repo would be better, I guess.

**Comment by horazont** [comment]
This looks like maybe a version mismatch between pyasn1_modules and pyasn1. Make sure to install both the same way.

**Comment by cknoll** [comment]
`pip install --upgrade pyasn1` (inside the venv) fixed that. It installed version 0.4.2

IMHO The problem was that pyasn1_modules was installed automatically in the venv but pyasn1 was used from the site-packages (version 0.1.9) where it lies around from debian package `python3-pyasn1` (installed due to unrelated reasons).

While this is easy to fix I still think this should be handled via `install_requires= ...` in setup.py of aioxmpp.

**Comment by horazont** [comment]
I’m not sure what an ``install_requires`` can do here? We would have to pin to a specific version of pyasn1 or pyasn1_modules, which I don’t want to.

**Comment by cknoll** [comment]
What about `pyasn1>=0.4`like in the case of `aiosasl>=0.3`?

**Comment by horazont** [comment]
But we don’t strictly require ``pyasn1>=0.4``. This is a dependency problem with ``pyasn1_modules``, not ``aioxmpp``, if I understand the situation correctly.

FWIW, the other alternative should be to install python3-pyasn1-modules outside the venv.

**Comment by cknoll** [comment]
Hmm. You are right. *Someone* should open an issue there.

Nevertheless there is the pragmatic view: fixing that dependency might prevent problems for other testers leaving more time and motivation for actual testing of jabbercat.

**Comment by horazont** [comment]
I’ll leave a note in the testing guide.

I also think that this might be due to pip not ensuring that dependencies w.r.t. ``--system-site-packages`` are actually fulfilled, instead of a missing dependency declaration at ``pyasn1_modules``.

At which point the question is whether:

1. simplify the testing process by removing ``--system-site-packages``, with the downside that people will install things like PyOpenSSL into a venv, **or**
2. add another note to guide people on what to do…

**Comment by cknoll** [comment]
I think the cleanest way is what you mentioned above:
>  install python3-pyasn1-modules outside the venv.

I tried it:
 1. uninstalled pyasn1 and pyasn1_modules via pip in the venv,
 2. installed python3-pyasn1-modules via apt)

→ jabbercat does start.

This would mean to add some additional dependencies to the guide but no extra prosa notes which are tedious to process.
