### ISSUE TITLE
ValueError when closing without enabled accounts

### ISSUE THREAD

**Issue by cknoll** [jabbercat/jabbercat#46]
Reproduce: `make run-debug`, wait until the window appears, close the window.

Error:  `ValueError: Set of coroutines/Futures is empty.`

see attached log:
[jabbercat-2018-02-27T13-54-58.log](https://github.com/jabbercat/jabbercat/files/1762685/jabbercat-2018-02-27T13-54-58.log)

**Comment by horazont** [comment]
Thanks. This happens because no accounts are configured.

**Comment by horazont** [comment]
Fixed with jclib commit [``928a4b2``](https://github.com/jabbercat/jclib/commit/928a4b24fcb02610ae5461f15b68da84dbd7ff03).
