### ISSUE TITLE
Double-clicking a contact leads to rename

### ISSUE THREAD

**Issue by ge0rg** [jabbercat/jabbercat#5]
Sometimes double-clicking a contact inadvertently makes the name editable and then cancels the action again, leading to a "Renaming contact 'foo' to 'foo'" action.

Please do not cause roster pushes for such events (when the name didn't really change), or even better: have a smarter behavior that doesn't misinterpret double-clicks as rename-abort.

**Comment by horazont** [comment]
A slow double-click leads to a rename, a fast doesn’t. This is common in lists. I’m not sure we should change that.

Regarding emitting a roster change, yes, indeed, that should be avoided when no change has actually been made.

**Comment by horazont** [comment]
A null rename (i.e. rename without a change) should not emit a roster update anymore.

Opinions on the slow-double-click-causes-edit thing?

**Comment by horazont** [comment]
Given the lack of opinions, I’ll leave it as it is. It is standard-ish behaviour and the timing which makes a double-click either slow (triggering a rename) or fast (opening a conversation) should integrate with the desktop environment nicely.

Feel free to re-open if you have additional arguments.
