### ISSUE TITLE
The Autojoin flag of MUC bookmarks is ignored

### ISSUE THREAD

**Issue by sebastianriese** [jabbercat/jabbercat#60]
MUC bookmarks where `autojoin="1"` should be joined automatically when jabbercat conects

**Comment by horazont** [comment]
Hah. Yeah, that went lost during the re-write of the roster/bookmark/conversation code in jclib.

(I also didn’t implement it again yet because it’s rather annoying when testing :-)).

I think this should be done in coordination with #49.

**Comment by sebastianriese** [comment]
Yup, it probably should be disabled for testing. While we're at it, we should also add support for serializing MUC roster items to the roster cache, I started to work on that one, but I did not entirely figure out how the roster cache works for normal roster entries and gave up.

**Comment by horazont** [comment]
Terrifying.

**Comment by horazont** [comment]
Autojoin has been implemented in jabbercat/jclib@41118c986f9353c1be618765764b3c9745f13541.
