### ISSUE TITLE
select avatar button does nothing

### ISSUE THREAD

**Issue by cknoll** [jabbercat/jabbercat#66]
After adding a new account I get a dialog window with a "Select avatar ..." button.

That button seems to do nothing. Not even a debug messages appears in the konsole.

**Comment by horazont** [comment]
As [documented in the testing notes](https://jabbercat.org/testing/#known-issues), this is not implemented yet at all. See also #62.

(Eventually, there is going to be support for that.)

**Comment by cknoll** [comment]
having the testing notes memorized is not really realistic :-) What about changing the button text to something like "Select avatar ... (not yet implemented)". Or at least leave a debug message in the terminal. Testing users then know that they do not have to bother. I guess there might be more situations like this.

**Comment by horazont** [comment]
The UI has just been removed as mentioned in #62.
