### ISSUE TITLE
Couldn't paste a MUC-JID-URL

### ISSUE THREAD

**Issue by mdosch** [jabbercat/jabbercat#7]
I copied 'xmpp:jabbercat@conference.zombofant.net?join' to my clipboard and wanted to paste it in 'Join a group chat' but it didn't work.

With only the JID 'jabbercat@conference.zombofant.net' in clipboard pasting worked.

**Comment by horazont** [comment]
Good idea, special handling of MUC URLs would improve the UI indeed.

(If you’re interested in the technical details: a MUC URL is not a valid JID, thus it is rejected by the edit widgets validator.)

**Comment by horazont** [comment]
That should work now, care to give it a shot?

**Comment by mdosch** [comment]
I can confirm it works now.
