### ISSUE TITLE
Implement global JID metadata service akin to Avatar

### ISSUE THREAD

**Issue by horazont** [jabbercat/jabbercat#73]
## Description

Now that we’ve gained experience with the flow, I think we can move forward implementing the global JID metadata service. It should be a common interface to obtain JID properties:

* ``avatar``: The avatar picture
* ``display_name``: A human-friendly display name: e.g. roster name, MUC subject or joined aggregation of member names
* ``presence``: Presence status
* ``subscription``: Subscription status
* ``last_message``: (for conversation JIDs) last message of the conversation
* ``conversation_type``: MUC vs. one-on-one vs. MIX vs. MUC-PM vs. undefined (for non-conversation JIDs)
* …

The workflow should be like this:

* non-coroutine ``get`` method: This returns the information currently available in the cache, and if the cache is stale, it queues a refresh in the background. This must be super-efficient because it will be called while drawing things.
* ``changed`` signal: Fires whenever the cached property of a JID changes. Must also fire when an asynchronous cache refresh finishes (and returns a result different than the one in the cache).
* coroutine ``fetch`` method: Like ``get``, but if the cache is stale, refresh blockingly. If it causes the cached data to change, also emits ``changed``.

Implementations may push-update the cache, so that it gets refreshed without needing to call ``get`` (e.g. for ``presence``, ``subscription``, ``display_name``, …).

The service should be generic. Different providers should be able to register different properties. Consumers should be able to subscribe to a subset of properties and/or possibly to a subset of JIDs.

May expire stuff out of the in-memory cache (this does not emit a ``changed`` signal) and/or swap it out to disk.

This will allow us to move forward with #47 and other new features.

## Interface draft

```python
# may be implemented e.g. by jabbercat.avatar
class Provider:
    on_changed = aioxmpp.callbacks.Signal()
    
    @abc.abstractmethod
    def get(self, account: Account, address: aioxmpp.JID):
        pass
    
    @abc.abstractmethod
    @asyncio.coroutine
    def fetch(self, account: Account, address: aioxmpp.JID):
        pass
    
    
    
class MetadataCache:
    on_any_changed = aioxmpp.callbacks.Signal()
    
    def register_provider(self, 
                          key: object, 
                          provider: Provider):
        pass
    
    def get(self, account: Account, address: aioxmpp.JID, key: object):
        pass
    
    @asyncio.coroutine
    def fetch(self, account: Account, address: aioxmpp.JID, key: object):
        pass
    
    def changed_signal(self, key: object) -> aioxmpp.callbacks.AdHocSignal:
        pass
```

**Comment by ge0rg** [comment]
Great writeup, I'm aiming for a similar (albeit less featureful) API in yaxim.

Suggestions:

- have bare JIDs for users and MUCs and full JIDs for MUC-PM chats
- represent incoming CSNs as presence (annotation), or at least as a separate entity
- for MUCs, either map your own joining-status as presence or have a separate field for that (i.e. joined, kicked, currently joining, ...)

**Comment by horazont** [comment]
> have bare JIDs for users and MUCs and full JIDs for MUC-PM chats

That’s what we’re already doing; the "Conversation JID" is the JID which identifies a conversation; for everything but MUC PMs, that’s a bare JID.

> represent incoming CSNs as presence (annotation), or at least as a separate entity

CSNs are a good point, I’m not sure how we’ll handle those. It’s possible that we need another (layer of) cache here, because they’re properties of Members in Conversations. We might not want to identify those by their JIDs, but by their Conversation JID + Occupant IDs (which is different from the JID only for anonymous MUCs, but the difference matters).

> for MUCs, either map your own joining-status as presence or have a separate field for that (i.e. joined, kicked, currently joining, ...)

Separate field probably makes sense.

Thanks.

**Comment by horazont** [comment]
Work on this has started in jabbercat/jclib@34e76375970b7fe549d32388c3b1b2812ffa0d12.

**Comment by horazont** [comment]
Service works as intended. We now need to add providers as needed. Closing this.
