### ISSUE TITLE
Chat view: allow copying of links / implement contex menu

### ISSUE THREAD

**Issue by ge0rg** [jabbercat/jabbercat#81]
When right-clicking on a highlighted link, I expected a popup menu with choices like:

* open in browser
* copy link
* ...

However, nothing happened :)

**Comment by horazont** [comment]
Yeah, I do expect that popup too. I tried various approaches to make it happen (most notably including those which appear to work for other people and those in the official documentation). I have no idea why it doesn’t happen.

Thanks for writing this down, I hadn’t gotten around to that yet.

**Comment by horazont** [comment]
Fixed in 337f9aa.
