### ISSUE TITLE
Inconsistent appearance of messages due to delivery state icons

### ISSUE THREAD

**Issue by sebastianriese** [jabbercat/jabbercat#93]
If your font is sufficiently small, the delivery state icons in the message view will increase the distance between your own chat lines compared to those from other participants (if you write multiple messages in a row). Also, the line dances around as the icon appears.

**Comment by horazont** [comment]
This might be fixable by making the image size dependent on some font metric like em.

**Comment by horazont** [comment]
Fixed with 033d091947330457f7365f2e9e08c6ac7ca5e6d6.
